src/Entity/Profile.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProfileRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable
 */
class Profile implements \Serializable
{
    const VISIBILITY_PUBLIC = 'PUBLIC';

    const VISIBILITY_AUTHENTICATED = 'AUTHENTICATED';

    const VISIBILITY_PRIVATE = 'PRIVATE';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="profile", cascade={"persist"})
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * @ORM\Column(name="type", type="string")
     */
    private $visibility = self::VISIBILITY_PUBLIC;

    /**
     * @Assert\File(mimeTypes={"image/png", "image/jpeg", "image/pjpeg"})
     * @Vich\UploadableField(mapping="avatar_image", fileNameProperty="avatar_name")
     */
    private $avatarImage;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, name="avatar_name")
     */
    private $avatarName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $phone;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Education", mappedBy="profile", cascade={"persist"}, orphanRemoval=true)
     */
    private $educations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Experience", mappedBy="profile", cascade={"persist"}, orphanRemoval=true)
     */
    private $experiences;

    /**
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(name="modified", type="datetime", nullable=true)
     */
    private $modified;

    public function __construct()
    {
        $this->educations = new ArrayCollection();
        $this->experiences = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     */
    public function onPrePersist()
    {
        $this->created = new \DateTime('now');
    }

    /**
     * @ORM\PreUpdate
     */
    public function onPreUpdate()
    {
        $this->modified = new \DateTime('now');
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function __toString()
    {
        return self::class;
    }

    /**
     * @return mixed
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @param mixed $address
     */
    public function setAddress($address): void
    {
        $this->address = $address;
    }

    /**
     * @return mixed
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * @param mixed $phone
     */
    public function setPhone($phone): void
    {
        $this->phone = $phone;
    }

    /**
     * @return mixed
     */
    public function getEducations()
    {
        return $this->educations;
    }

    /**
     * @param mixed $educations
     */
    public function setEducations($educations)
    {
        $this->educations = $educations;
    }

    /**
     * @return mixed
     */
    public function getExperiences()
    {
        return $this->experiences;
    }

    /**
     * @param mixed $experiences
     */
    public function setExperiences($experiences)
    {
        $this->experiences = $experiences;
    }

    public function setDefaultRole()
    {
        $this->getUser()->setRoles(['ROLE_USER']);
    }

    /**
     * @return mixed
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * @param mixed $created
     */
    public function setCreated($created): void
    {
        $this->created = $created;
    }

    /**
     * @return mixed
     */
    public function getVisibility()
    {
        return $this->visibility;
    }

    /**
     * @param mixed $visibility
     */
    public function setVisibility($visibility): void
    {
        $this->visibility = $visibility;
    }


    public function getFullName()
    {
        if (!empty($this->firstName) && !empty($this->lastName)) {
            return sprintf('%s %s', $this->firstName, $this->lastName);
        }

        return $this->getUser()->getUsername();
    }

    public function getInitials()
    {
        if (!empty($this->firstName) && !empty($this->lastName)) {
            return $this->firstName[0] . $this->lastName[0];
        }

        return $this->getUser()->getUsername()[0];
    }

    public function getUsername()
    {
        return $this->getUser()->getUserName();
    }

    /**
     * @return mixed
     */
    public function getAvatarImage()
    {
        return $this->avatarImage;
    }

    /**
     * @param mixed $avatarImage
     */
    public function setAvatarImage(File $avatarImage)
    {
        $this->avatarImage = $avatarImage;

        if ($avatarImage) {
            $this->modified = new \DateTime('now');
        }
    }

    /**
     * @return mixed
     */
    public function getAvatarName()
    {
        return $this->avatarName;
    }

    /**
     * @param mixed $avatarName
     */
    public function setAvatarName($avatarName)
    {
        $this->avatarName = $avatarName;
    }

    /**
     * String representation of object
     * @link https://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        $this->avatarImage = base64_encode($this->avatarImage);
    }

    /**
     * Constructs the object
     * @link https://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        $this->avatarImage = base64_decode($this->avatarImage);
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    public const ROLE_USER = 'ROLE_USER';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Profile", mappedBy="user", cascade={"persist"})
     **/
    private $profile;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Company", mappedBy="user", cascade={"persist"})
     */
    private $company;

    /**
     * @ORM\Column(type="boolean", nullable=true, name="is_verified")
     */
    private $isVerified;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @var String
     */
    protected $plainPassword;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $confirmationCode;


    public function __construct()
    {
        $this->roles = [self::ROLE_USER];
        $this->enabled = false;
        $this->companies = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * @param mixed $companies
     */
    public function setCompany($company)
    {
        $this->company = $company;
        $this->company->setUser($this);
        return $this;
    }

    /**
     * @return mixed
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * @param mixed $profile
     */
    public function setProfile($profile)
    {
        $this->profile = $profile;
        $this->profile->setUser($this);
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = self::ROLE_USER;

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

    /**
     * @return mixed
     */
    public function getisVerified(): bool
    {
        return $this->isVerified;
    }

    /**
     * @param mixed $isVerified
     */
    public function setIsVerified($isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return string
     */
    public function getConfirmationCode(): string
    {
        return $this->confirmationCode;
    }

    /**
     * @param string $confirmationCode
     */
    public function setConfirmationCode(string $confirmationCode): void
    {
        $this->confirmationCode = $confirmationCode;
    }
}

templates/my-company/_side-menu.html.twig
{% set route = app.request.attributes.get('_route') %}

<div class="dashboard-sidebar">
    <div class="company-info">
        <div class="thumb">
            {% if app.user.company.logoName %}
                <img src="{{ vich_uploader_asset(app.user.company, 'logoImage') }}" class="img-fluid" alt="">
            {% else %}
                <img src="{{ asset('images/no-company.png') }}" class="img-fluid" alt="">
            {% endif %}
        </div>
        <div class="company-body">
            <h5>{{ app.user.company.name }}</h5>
            <span>{{ app.user.company.username }}</span>
        </div>
    </div>

    {# TODO: Create progress bar feature according to profile completeness #}
    {#<div class="profile-progress">
        <div class="progress-item">
            <div class="progress-head">
                <p class="progress-on">Company</p>
            </div>
            <div class="progress-body">
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 0;"></div>
                </div>
                <p class="progress-to">70%</p>
            </div>
        </div>
    </div>
    #}
    <div class="dashboard-menu">
        <ul>
            <li {{ route ==  'my_company_index' ? 'class="active"' }}><i class="fas fa-home"></i><a href="{{ path('my_company_index') }}">Dashboard</a></li>
            <li {{ route ==  'my_company_settings' ? 'class="active"' }}><i class="fas fa-user"></i><a href="{{ path('my_company_settings') }}">Edit Profile</a></li>
            <li {{ route ==  'my_company_jobs' ? 'class="active"' }}><i class="fas fa-briefcase"></i><a href="{{ path('my_company_jobs') }}">Manage Jobs</a></li>
            <li {{ route ==  'my_company_job_new' ? 'class="active"' }}><i class="fas fa-plus-square"></i><a href="{{ path('my_company_job_new') }}">Post New Job</a></li>
            <li {{ route ==  'my_company_candidates' ? 'class="active"' }}><i class="fas fa-users"></i><a href="#">Manage Candidates</a></li>
            <li {{ route ==  'my_company_resumes' ? 'class="active"' }}><i class="fas fa-heart"></i><a href="#">Shortlisted Resumes</a></li>
            <li {{ route ==  'my_company_messages' ? 'class="active"' }}><i class="fas fa-comment"></i><a href="#">Message</a></li>
        </ul>
        <ul class="delete">
            <li><i class="fas fa-power-off"></i><a href="{{ path('security_logout') }}">Logout</a></li>
            <li><i class="fas fa-trash-alt"></i><a href="#" data-toggle="modal" data-target="#modal-delete">Delete Profile</a></li>
        </ul>

        <!-- Modal -->
        <div class="modal fade modal-delete" id="modal-delete" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <h4><i data-feather="trash-2"></i>Delete Account</h4>
                        <p>Are you sure! You want to delete your profile. This can't be undone!</p>
                        <form action="#">
                            <div class="form-group">
                                <input type="password" class="form-control" placeholder="Enter password">
                            </div>
                            <div class="buttons">
                                <button class="delete-button">Save Update</button>
                                <button class="">Cancel</button>
                            </div>
                            <div class="form-group form-check">
                                <input type="checkbox" class="form-check-input" checked="">
                                <label class="form-check-label">You accepts our <a href="#">Terms and Conditions</a> and
                                    <a href="#">Privacy Policy</a></label>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/my-company/edit-job.html.twig
{% extends 'base-dashboard.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <!-- Breadcrumb -->
    <div class="alice-bg padding-top-70 padding-bottom-70">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="breadcrumb-area">
                        <h1>Employer Dashboard</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Employer Dashboard</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <div class="alice-bg section-padding-bottom">
        <div class="container no-gliters">
            <div class="row no-gliters">
                <div class="col">
                    <div class="dashboard-container">
                        <div class="dashboard-content-wrapper">
                            {{ form_start(form, {'attr': {'class': 'dashboard-form job-post-form'}}) }}
                            <div class="dashboard-section basic-info-input">
                                <h4><i data-feather="user-check"></i>Post A Job</h4>
                                {{ form_row(form.title) }}
                                {{ form_row(form.contract) }}
                                {{ form_row(form.country) }}
                                {{ form_row(form.state) }}
                                {{ form_row(form.salary) }}
                                {{ form_row(form.categories) }}
                                {{ form_row(form.description) }}
                            </div>
                            {{ form_end(form) }}
                        </div>
                        {% include "my-company/_side-menu.html.twig" %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/my-company/new-job.html.twig
{% extends 'base-dashboard.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    <!-- Breadcrumb -->
    <div class="alice-bg padding-top-70 padding-bottom-70">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="breadcrumb-area">
                        <h1>Employer Dashboard</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Employer Dashboard</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <div class="alice-bg section-padding-bottom">
        <div class="container no-gliters">
            <div class="row no-gliters">
                <div class="col">
                    <div class="dashboard-container">
                        <div class="dashboard-content-wrapper">
                            {{ form_start(form, {'attr': {'class': 'dashboard-form job-post-form'}}) }}
                            <div class="dashboard-section basic-info-input">
                                <h4><i data-feather="user-check"></i>Post A Job</h4>
                                {{ form_row(form.title) }}
                                {{ form_row(form.contract) }}
                                {{ form_row(form.country) }}
                                {{ form_row(form.state) }}
                                {{ form_row(form.salary) }}
                                {{ form_row(form.categories) }}
                                {{ form_row(form.description, {'attr' : {'class' : 'tinymce-editor tinymce-editor-1'}}) }}
                            </div>
                            {{ form_end(form) }}
                        </div>
                        {% include "my-company/_side-menu.html.twig" %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/my-company/profile.html.twig
{% extends 'base-dashboard.html.twig' %}
{% form_theme form _self %}

{% block title %}{% endblock %}

{% block vich_image_widget %}
    {% spaceless %}
        <div class="update-photo">
            <img class="image" src="{{ image_uri }}" alt="">
        </div>
        <div class="file-upload">
            {{ form_widget(form.file) }}
            Change Avatar
        </div>
    {% endspaceless %}
{% endblock %}

{% block file_widget %}
    {% spaceless %}
        {% set type = type|default('file') %}
        <input type="{{ type }}" {{ block('widget_attributes') }} class="file-input" />
    {% endspaceless %}
{% endblock %}


{% block body %}
    <!-- Breadcrumb -->
    <div class="alice-bg padding-top-70 padding-bottom-70">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="breadcrumb-area">
                        <h1>Dashboard</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <div class="alice-bg section-padding-bottom">
        <div class="container no-gliters">
            <div class="row no-gliters">
                <div class="col">
                    <div class="dashboard-container">
                        <div class="dashboard-content-wrapper">
                            {% include '_parts/messages.html.twig' %}
                            <form action="{{ path('my_profile_settings') }}" class="dashboard-form">
                                <div class="dashboard-section upload-profile-photo">
                                    {{ form_widget(form.avatarImage) }}
                                </div>
                                <div class="dashboard-section basic-info-input">
                                    <h4><i data-feather="user-check"></i>Basic Info</h4>
                                    {{ form(form) }}
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label"></label>
                                        <div class="col-sm-9">
                                            <button class="button">Save Change</button>
                                        </div>
                                    </div>
                                </div>
                            </form>

                            <div class="dashboard-section basic-info-input">
                                <h4><i data-feather="lock"></i>Change Password</h4>
                                <form action="{{ path('my_account_password') }}" class="dashboard-form" method="POST">
                                    {{ form_row(userForm.email) }}
                                    {{ form_row(userForm.plainPassword) }}
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label"></label>
                                        <div class="col-sm-9">
                                            <button class="button">Save Change</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div class="dashboard-sidebar">
                            <div class="user-info">
                                <div class="thumb">
                                    <img src="{{ vich_uploader_asset(profile, 'avatarImage') }}" class="img-fluid" alt="">
                                </div>
                                <div class="user-body">
                                    <h5>{{ profile.fullName }}</h5>
                                    <span>{{ profile.username }}</span>
                                </div>
                            </div>
                            <div class="profile-progress">
                                <div class="progress-item">
                                    <div class="progress-head">
                                        <p class="progress-on">Profile</p>
                                    </div>
                                    <div class="progress-body">
                                        <div class="progress">
                                            <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 0;"></div>
                                        </div>
                                        <p class="progress-to">70%</p>
                                    </div>
                                </div>
                            </div>
                            <div class="dashboard-menu">
                                <ul>
                                    <li><i class="fas fa-home"></i><a href="{{ path('my_account_index') }}">Dashboard</a></li>
                                    <li class="active"><i class="fas fa-user"></i><a href="dashboard-edit-profile.html">Edit Profile</a></li>
                                    <li><i class="fas fa-file-alt"></i><a href="resume.html">Resume</a></li>
                                    <li><i class="fas fa-edit"></i><a href="edit-resume.html">Edit Resume</a></li>
                                    <li><i class="fas fa-heart"></i><a href="dashboard-bookmark.html">Bookmarked</a></li>
                                    <li><i class="fas fa-check-square"></i><a href="dashboard-applied.html">Applied Job</a></li>
                                    <li><i class="fas fa-comment"></i><a href="dashboard-message.html">Message</a></li>
                                    <li><i class="fas fa-calculator"></i><a href="dashboard-pricing.html">Pricing Plans</a></li>
                                </ul>
                                <ul class="delete">
                                    <li><i class="fas fa-power-off"></i><a href="{{ path('security_logout') }}">Logout</a></li>
                                    <li><i class="fas fa-trash-alt"></i><a href="#" data-toggle="modal" data-target="#modal-delete">Delete Profile</a></li>
                                </ul>

                                <!-- Modal -->
                                <div class="modal fade modal-delete" id="modal-delete" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-body">
                                                <h4><i data-feather="trash-2"></i>Delete Account</h4>
                                                <p>Are you sure! You want to delete your profile. This can't be undone!</p>

                                                <form action="#">
                                                    <div class="form-group">
                                                        <input type="password" class="form-control" placeholder="Enter password">
                                                    </div>
                                                    <div class="buttons">
                                                        <button class="delete-button">Save Update</button>
                                                        <button class="">Cancel</button>
                                                    </div>
                                                    <div class="form-group form-check">
                                                        <input type="checkbox" class="form-check-input" checked="">
                                                        <label class="form-check-label">You accepts our <a href="#">Terms and Conditions</a> and <a href="#">Privacy Policy</a></label>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}